apiVersion: v1
kind: Pod
metadata:
  name: test-vlan50
  namespace: webservices
  annotations:
    k8s.v1.cni.cncf.io/networks: '[{ "name": "vlan50-net", "ips": ["10.0.50.123/24"] }]'
spec:
  containers:
  - name: pause
    image: registry.k8s.io/pause:3.9
