# vlan50-net.yaml
# This file defines a NetworkAttachmentDefinition for a VLAN network using Multus CNI.
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vlan50-net
  namespace: webservices
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "vlan50-net",
      "plugins": [
        {
          "type": "macvlan",
          "master": "eth1",
          "mode": "bridge",
          "vlan": 50,
          "ipam": {
            "type": "host-local",
            "subnet": "10.0.50.0/24",
            "gateway": "10.0.50.1",
            "rangeStart": "10.0.50.100",
            "rangeEnd": "10.0.50.149"
          }
        }
      ]
    }
