# vlan50-net.yaml
# This file defines a NetworkAttachmentDefinition for a VLAN50 network using Multus CNI with DHCP IPAM.
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vlan50-net
  namespace: webservices
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "name": "vlan50-net",
      "plugins": [
        {
          "type": "macvlan",
          "master": "ens19",
          "mode": "bridge",
          "vlan": 50,
          "ipam": {
            "type": "dhcp"
          }
        }
      ]
    }
