#vlan50-test.yaml
# This file defines a Pod that uses the vlan50-net NetworkAttachmentDefinition created by Multus
apiVersion: v1
kind: Pod
metadata:
  name: vlan50-test
  namespace: webservices
  annotations:
    k8s.v1.cni.cncf.io/networks: vlan50-net
spec:
  containers:
  - name: test
    image: busybox
    command: ["sleep", "3600"]
