# vlan50-net.yaml
# This file defines a NetworkAttachmentDefinition for a VLAN network using Multus
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: vlan50-net
  namespace: webservices
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "macvlan",
    "master": "ens19",
    "mode": "bridge",
    "ipam": {
      "type": "static",
      "addresses": [
        {
          "address": "10.0.50.101/24",
          "gateway": "10.0.50.1"
        }
      ],
      "dns": {
        "nameservers": ["10.0.50.1"]
      }
    }
  }'

